[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_port = COM6

lib_deps =
    adafruit/DHT sensor library @ ^1.4.4
    spaziochirale/Chirale_TensorFlowLite @ 2.0.0
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git

build_flags =
    -DTF_LITE_MICRO_ALLOW_REPEATED_OPS
    -O2
    -Wl,--gc-sections

board_build.partitions = huge_app.csv
upload_speed = 921600